#!/usr/bin/env python3
"""Create or update one GitHub owner handoff issue for actionable LLM digests."""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from automation.io import load_json


REPORTS_DIR = ROOT / "automation" / "reports"
DEFAULT_DIGEST_PATH = REPORTS_DIR / "llm-owner-digest.json"
DEFAULT_MARKDOWN_PATH = REPORTS_DIR / "llm-owner-digest.md"
DEFAULT_TITLE = "LLM Owner Digest: Action Needed"
ACTIONABLE_STATES = {"owner_review_needed", "ready_for_intake", "blocked_or_failed"}


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT) if path.is_relative_to(ROOT) else path)


def resolve_path(value: str) -> Path:
    path = Path(value)
    return path if path.is_absolute() else ROOT / path


def run_url(repository: str, server_url: str, explicit_url: str | None = None) -> str:
    if explicit_url:
        return explicit_url
    run_id = os.environ.get("GITHUB_RUN_ID", "")
    if run_id:
        return f"{server_url.rstrip('/')}/{repository}/actions/runs/{run_id}"
    return ""


def read_markdown(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def render_issue_body(digest: dict[str, Any], markdown: str, workflow_url: str) -> str:
    counts = digest.get("counts", {}) if isinstance(digest.get("counts"), dict) else {}
    lines = [
        "<!-- llm-owner-digest-handoff -->",
        "# LLM Owner Digest: Action Needed",
        "",
        "This issue was generated by the no-write LLM auto-review queue because the owner digest needs attention.",
        "",
        "## Summary",
        "",
        f"- State: `{digest.get('state', '')}`",
        f"- Recommended next action: {digest.get('recommended_next_action', '')}",
        f"- Generated at: `{digest.get('generated_at', '')}`",
        f"- Candidate topics: `{counts.get('candidate_topics', 0)}`",
        f"- Needs owner review: `{counts.get('digest_needs_review', 0)}`",
        f"- Ready for intake: `{counts.get('digest_ready_for_intake', 0)}`",
        f"- Blocked or failed: `{counts.get('digest_failed', 0)}`",
        f"- Resolved by decision: `{counts.get('resolved_by_owner_decision', 0)}`",
    ]
    if workflow_url:
        lines.append(f"- Workflow run: {workflow_url}")
    lines.extend(
        [
            "",
            "## Safety",
            "",
            "- This issue does not approve public copy.",
            "- The underlying automation did not edit content, backlog, manifests, PRs, or production state.",
            "- Public content still requires exact proposed text, owner approval, apply-preview, apply-approved, and strict QA.",
        ]
    )
    if markdown:
        lines.extend(["", "## Digest", "", markdown])
    return "\n".join(lines)


def render_resolved_issue_body(digest: dict[str, Any], workflow_url: str) -> str:
    counts = digest.get("counts", {}) if isinstance(digest.get("counts"), dict) else {}
    lines = [
        "<!-- llm-owner-digest-handoff -->",
        "# LLM Owner Digest: Resolved",
        "",
        "The latest no-write LLM owner digest no longer needs owner action, so this handoff issue was closed automatically.",
        "",
        "## Latest Digest",
        "",
        f"- State: `{digest.get('state', '')}`",
        f"- Recommended next action: {digest.get('recommended_next_action', '')}",
        f"- Generated at: `{digest.get('generated_at', '')}`",
        f"- Candidate topics: `{counts.get('candidate_topics', 0)}`",
        f"- Needs owner review: `{counts.get('digest_needs_review', 0)}`",
        f"- Ready for intake: `{counts.get('digest_ready_for_intake', 0)}`",
        f"- Blocked or failed: `{counts.get('digest_failed', 0)}`",
        f"- Resolved by decision: `{counts.get('resolved_by_owner_decision', 0)}`",
    ]
    if workflow_url:
        lines.append(f"- Workflow run: {workflow_url}")
    lines.extend(
        [
            "",
            "## Safety",
            "",
            "- This closure does not approve public copy.",
            "- The underlying automation did not edit content, backlog, manifests, PRs, or production state.",
        ]
    )
    return "\n".join(lines)


def github_request(
    api_url: str,
    token: str,
    method: str,
    path: str,
    payload: dict[str, Any] | None = None,
) -> Any:
    body = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        f"{api_url.rstrip('/')}{path}",
        data=body,
        method=method,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            text = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        details = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API {method} {path} failed with {exc.code}: {details}") from exc
    return json.loads(text) if text else {}


def find_open_issue(api_url: str, token: str, repository: str, title: str) -> dict[str, Any] | None:
    issues = github_request(api_url, token, "GET", f"/repos/{repository}/issues?state=open&per_page=100")
    if not isinstance(issues, list):
        return None
    for issue in issues:
        if issue.get("pull_request"):
            continue
        if issue.get("title") == title:
            return issue
    return None


def upsert_issue(
    digest: dict[str, Any],
    markdown: str,
    repository: str,
    token: str,
    api_url: str,
    server_url: str,
    title: str,
    explicit_run_url: str | None,
) -> dict[str, Any]:
    body = render_issue_body(digest, markdown, run_url(repository, server_url, explicit_run_url))
    existing = find_open_issue(api_url, token, repository, title)
    if existing:
        issue = github_request(
            api_url,
            token,
            "PATCH",
            f"/repos/{repository}/issues/{existing['number']}",
            {"title": title, "body": body},
        )
        return {"action": "updated", "issue_number": issue.get("number"), "issue_url": issue.get("html_url")}
    issue = github_request(
        api_url,
        token,
        "POST",
        f"/repos/{repository}/issues",
        {"title": title, "body": body},
    )
    return {"action": "created", "issue_number": issue.get("number"), "issue_url": issue.get("html_url")}


def close_resolved_issue(
    digest: dict[str, Any],
    repository: str,
    token: str,
    api_url: str,
    server_url: str,
    title: str,
    explicit_run_url: str | None,
) -> dict[str, Any]:
    existing = find_open_issue(api_url, token, repository, title)
    if not existing:
        return {"action": "skipped_non_actionable", "issue_number": None, "issue_url": None}
    body = render_resolved_issue_body(digest, run_url(repository, server_url, explicit_run_url))
    issue = github_request(
        api_url,
        token,
        "PATCH",
        f"/repos/{repository}/issues/{existing['number']}",
        {
            "title": title,
            "body": body,
            "state": "closed",
            "state_reason": "completed",
        },
    )
    return {"action": "closed_resolved", "issue_number": issue.get("number"), "issue_url": issue.get("html_url")}


def build_summary(
    digest_path: Path,
    markdown_path: Path,
    repository: str,
    token: str,
    api_url: str,
    server_url: str,
    title: str,
    explicit_run_url: str | None,
    dry_run: bool,
) -> dict[str, Any]:
    digest = load_json(digest_path)
    state = digest.get("state", "")
    actionable = state in ACTIONABLE_STATES
    summary: dict[str, Any] = {
        "state": state,
        "actionable": actionable,
        "digest_path": rel(digest_path),
        "markdown_path": rel(markdown_path),
        "issue_title": title,
        "action": "skipped_non_actionable",
        "issue_number": None,
        "issue_url": None,
        "safety": "Owner issue handoff only. No content, backlog, manifest, PR, or production files were modified.",
    }
    if not actionable:
        if dry_run:
            summary.update(
                {
                    "action": "dry_run_non_actionable",
                    "resolved_issue_body": render_resolved_issue_body(
                        digest,
                        run_url(repository, server_url, explicit_run_url),
                    ),
                }
            )
            return summary
        if repository and token:
            summary.update(close_resolved_issue(digest, repository, token, api_url, server_url, title, explicit_run_url))
        return summary
    markdown = read_markdown(markdown_path)
    if dry_run:
        summary.update(
            {
                "action": "dry_run",
                "issue_body": render_issue_body(digest, markdown, run_url(repository, server_url, explicit_run_url)),
            }
        )
        return summary
    if not repository:
        raise RuntimeError("GITHUB_REPOSITORY or --repository is required for actionable owner issue handoff.")
    if not token:
        raise RuntimeError("GITHUB_TOKEN is required for actionable owner issue handoff.")
    summary.update(upsert_issue(digest, markdown, repository, token, api_url, server_url, title, explicit_run_url))
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description="Create/update one GitHub owner issue for actionable LLM owner digests.")
    parser.add_argument("--digest", default=str(DEFAULT_DIGEST_PATH), help="Path to llm-owner-digest.json.")
    parser.add_argument("--markdown", default=str(DEFAULT_MARKDOWN_PATH), help="Path to llm-owner-digest.md.")
    parser.add_argument("--repository", default=os.environ.get("GITHUB_REPOSITORY", ""), help="Repository in owner/name form.")
    parser.add_argument("--api-url", default=os.environ.get("GITHUB_API_URL", "https://api.github.com"), help="GitHub API base URL.")
    parser.add_argument("--server-url", default=os.environ.get("GITHUB_SERVER_URL", "https://github.com"), help="GitHub web base URL.")
    parser.add_argument("--run-url", help="Explicit workflow run URL.")
    parser.add_argument("--title", default=DEFAULT_TITLE, help="GitHub issue title to create/update.")
    parser.add_argument("--token-env", default="GITHUB_TOKEN", help="Environment variable containing the GitHub token.")
    parser.add_argument("--dry-run", action="store_true", help="Render the handoff without calling the GitHub API.")
    parser.add_argument("--json", action="store_true", help="Print a machine-readable summary.")
    args = parser.parse_args()

    try:
        summary = build_summary(
            resolve_path(args.digest),
            resolve_path(args.markdown),
            args.repository,
            os.environ.get(args.token_env, ""),
            args.api_url,
            args.server_url,
            args.title,
            args.run_url,
            args.dry_run,
        )
    except Exception as exc:
        if args.json:
            print(json.dumps({"error": str(exc)}, indent=2))
        else:
            print(f"LLM owner issue handoff failed: {exc}")
        return 1
    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"State: {summary['state']}")
        print(f"Action: {summary['action']}")
        if summary.get("issue_url"):
            print(f"Issue: {summary['issue_url']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
